name: PR Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Maven build
        run: mvn clean package